export const styles: Record<string, React.CSSProperties> = {
  popup: {
    position: "fixed",
    bottom: 20,
    right: 20,
    width: 320,
    maxWidth: "calc(100vw - 40px)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 16,
    background: "var(--color-header-bg)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 10,
    boxShadow: "0 6px 24px rgba(0,0,0,0.2)",
    color: "var(--color-text)",
    zIndex: 1000,
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    animation: "featurePopupIn 0.25s ease",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  sparkle: {
    display: "flex",
    alignItems: "center",
    color: "var(--color-branch)",
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 600,
  },
  closeBtn: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 2,
    border: "none",
    background: "transparent",
    color: "var(--color-text-secondary)",
    cursor: "pointer",
    borderRadius: 4,
  },
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  item: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  itemTitle: {
    fontSize: 13,
    fontWeight: 600,
  },
  itemDesc: {
    fontSize: 12,
    color: "var(--color-text-secondary)",
    lineHeight: 1.5,
  },
  dismissBtn: {
    alignSelf: "flex-end",
    padding: "6px 16px",
    fontSize: 13,
    fontWeight: 600,
    borderRadius: 6,
    border: "none",
    background: "var(--color-button-bg)",
    color: "var(--color-button-text)",
    cursor: "pointer",
  },
};
