// Space the focus banner keeps from the edge of the graph, and from the legend
// and shortcut panels it shares the top row with.
export const BANNER_EDGE_GAP = 12;

export const styles: Record<string, React.CSSProperties> = {
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    background: "var(--color-page-bg)",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    color: "var(--color-text)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "12px 20px",
    borderBottom: "1px solid var(--color-border-subtle)",
    background: "var(--color-header-bg)",
  },
  headerMobile: {
    gap: 8,
    padding: "8px 12px",
    flexWrap: "wrap" as const,
  },
  // On desktop the controls flow inline with the rest of the header. On mobile
  // they stack into a full-width column below the title so nothing overflows.
  controlsDesktop: {
    display: "contents",
  },
  controlsMobile: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "stretch",
    gap: 8,
    width: "100%",
  },
  iconRowDesktop: {
    display: "contents",
  },
  iconRowMobile: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 16,
  },
  backLink: {
    color: "var(--color-link)",
    textDecoration: "none",
    fontSize: 14,
    fontWeight: 500,
  },
  title: {
    fontSize: 18,
    fontWeight: 600,
    margin: 0,
  },
  titleMobile: {
    fontSize: 16,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  viewer: {
    fontSize: 13,
    color: "var(--color-text-secondary)",
    fontWeight: 500,
  },
  badge: {
    fontSize: 12,
    color: "var(--color-text-secondary)",
    marginLeft: "auto",
  },
  settingsBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
    border: "none",
    background: "transparent",
    color: "var(--color-text-secondary)",
    cursor: "pointer",
    borderRadius: 6,
    transition: "color 0.15s",
    opacity: 0.7,
  } as React.CSSProperties,
  menuItemRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    minWidth: 200,
  },
  menuToggleBtn: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: "3px 8px",
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 6,
    border: "1px solid var(--color-border-subtle)",
    cursor: "pointer",
    background: "transparent",
    color: "var(--color-text-secondary)",
    transition: "background 0.15s, color 0.15s",
  } as React.CSSProperties,
  lookbackLabel: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: "var(--color-text-secondary)",
    fontWeight: 500,
    whiteSpace: "nowrap" as const,
  },
  lookbackInput: {
    width: 42,
    padding: "3px 6px",
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 6,
    border: "1px solid var(--color-border-subtle)",
    background: "transparent",
    color: "var(--color-text)",
    textAlign: "center" as const,
    MozAppearance: "textfield" as const,
  },
  githubLink: {
    color: "var(--color-text-secondary)",
    display: "flex",
    alignItems: "center",
    marginLeft: 8,
    opacity: 0.7,
    transition: "opacity 0.15s",
  },
  content: {
    flex: 1,
    position: "relative" as const,
    overflow: "hidden",
  },
  statusContainer: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    marginTop: 80,
    gap: 12,
  },
  status: {
    textAlign: "center" as const,
    margin: 0,
    color: "var(--color-text-secondary)",
    fontSize: 15,
  },
  errorContainer: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    marginTop: 80,
    gap: 12,
  },
  error: {
    textAlign: "center" as const,
    margin: 0,
    color: "var(--color-error)",
    fontSize: 15,
  },
  retryBtn: {
    padding: "6px 16px",
    fontSize: 13,
    fontWeight: 600,
    borderRadius: 6,
    border: "1px solid var(--color-border-subtle)",
    background: "transparent",
    color: "var(--color-text)",
    cursor: "pointer",
    transition: "background 0.15s",
  },
  // Focused-PR banner, along the top of the graph. Its horizontal position is
  // measured rather than declared (see FocusBanner): centred on the graph, and
  // only pushed right by however much is needed to clear the legend and the
  // shortcut buttons. This declares the centred starting point used for the
  // first layout pass, before the measurement lands.
  focusBanner: {
    position: "absolute" as const,
    top: 12,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: 10,
    maxWidth: `calc(100% - ${BANNER_EDGE_GAP * 2}px)`,
    padding: "7px 14px",
    fontSize: 12,
    fontWeight: 500,
    color: "var(--color-text)",
    background: "var(--color-header-bg)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 999,
    boxShadow: "0 2px 8px var(--color-shadow)",
    zIndex: 60,
  },
  // A narrow screen has no room beside the panels, so there the banner sits
  // along the bottom instead — lifted clear of the "loading PRs" bar while that
  // is on screen.
  focusBannerMobile: {
    top: "auto",
    bottom: 12,
  },
  focusBannerMobileRaised: {
    top: "auto",
    bottom: 86,
  },
  // The full shorthand is repeated rather than overriding `borderColor` alone:
  // React warns when a rerender mixes a shorthand with one of its longhands.
  focusBannerProblem: {
    border: "1px solid var(--color-review-requested)",
  },
  focusBannerText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  focusBannerBtnDone: {
    color: "var(--color-ready)",
    border: "1px solid var(--color-ready)",
  },
  focusBannerBtn: {
    flexShrink: 0,
    padding: "3px 10px",
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 999,
    border: "1px solid var(--color-border-subtle)",
    background: "transparent",
    color: "var(--color-link)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  fetchingMoreBar: {
    position: "absolute" as const,
    bottom: 16,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
    padding: "8px 16px",
    fontSize: 12,
    fontWeight: 500,
    color: "var(--color-text-secondary)",
    background: "var(--color-header-bg)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
    zIndex: 50,
    whiteSpace: "nowrap" as const,
    minWidth: 260,
  },
  fetchingMoreContent: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  progressTrack: {
    width: "100%",
    height: 4,
    borderRadius: 2,
    background: "var(--color-border-subtle)",
    overflow: "hidden" as const,
  },
  progressFill: {
    height: "100%",
    borderRadius: 2,
    background: "var(--color-link, #58a6ff)",
    transition: "width 0.3s ease",
  },
};

export const dropdownStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    position: "relative",
  },
  // Full-width triggers/menus on mobile so taps are easy and menus can't spill
  // off the edge of a narrow screen.
  wrapperMobile: {
    width: "100%",
  },
  triggerMobile: {
    width: "100%",
    justifyContent: "space-between",
    padding: "8px 12px",
    fontSize: 13,
  },
  triggerLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  menuMobile: {
    width: "100%",
    minWidth: 0,
  },
  trigger: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 6,
    border: "1px solid var(--color-border-subtle)",
    cursor: "pointer",
    background: "transparent",
    color: "var(--color-text-secondary)",
    transition: "background 0.15s, color 0.15s",
    whiteSpace: "nowrap",
  },
  triggerAvatar: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    flexShrink: 0,
  },
  menu: {
    position: "absolute",
    top: "calc(100% + 4px)",
    left: 0,
    minWidth: 200,
    background: "var(--color-header-bg)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    boxShadow: "0 4px 16px rgba(0,0,0,0.2)",
    zIndex: 100,
    overflow: "hidden",
  },
  list: {
    maxHeight: 280,
    overflowY: "auto" as const,
  },
  item: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "7px 12px",
    fontSize: 13,
    border: "none",
    background: "transparent",
    color: "var(--color-text)",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 0.1s",
  },
  avatar: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    flexShrink: 0,
  },
  count: {
    color: "var(--color-text-secondary)",
    fontSize: 12,
    fontWeight: 400,
    flexShrink: 0,
  },
  divider: {
    height: 1,
    background: "var(--color-border-subtle)",
  },
};
