export const styles: Record<string, React.CSSProperties> = {
  container: {
    position: "absolute",
    top: 12,
    left: 12,
    zIndex: 10,
    background: "var(--color-card-bg)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    padding: "8px 12px",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    fontSize: 11,
    color: "var(--color-text)",
    boxShadow: "0 1px 3px var(--color-shadow)",
    pointerEvents: "none",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
    padding: 0,
    margin: 0,
    background: "transparent",
    border: "none",
    color: "inherit",
    font: "inherit",
    cursor: "pointer",
    pointerEvents: "auto",
  },
  title: {
    fontWeight: 600,
    fontSize: 12,
  },
  section: {
    fontWeight: 600,
    color: "var(--color-text-secondary)",
    fontSize: 10,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 3,
  },
  label: {
    color: "var(--color-text-secondary)",
  },
  nodeChip: {
    width: 24,
    height: 14,
    borderRadius: 4,
    border: "1.5px solid",
    flexShrink: 0,
  },
  badge: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 18,
    height: 18,
    borderRadius: 4,
    border: "1.5px solid",
    background: "var(--color-page-bg)",
  },
};
