export const styles: Record<string, React.CSSProperties> = {
  card: {
    position: "relative" as const,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
    gap: 3,
    padding: "8px 12px",
    width: "100%",
    height: "100%",
    boxSizing: "border-box",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    overflow: "visible",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    flexShrink: 0,
    marginTop: 3,
  },
  title: {
    color: "var(--color-text)",
    fontSize: 13,
    fontWeight: 600,
    lineHeight: "1.3",
    wordBreak: "break-word" as const,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden",
  },
  branch: {
    color: "var(--color-text-secondary)",
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    paddingLeft: 18,
  },
  labels: {
    display: "flex",
    flexWrap: "wrap" as const,
    alignContent: "flex-start" as const,
    gap: 3,
    paddingLeft: 18,
    minWidth: 0,
  },
  label: {
    display: "inline-flex",
    alignItems: "center",
    padding: "0 6px",
    height: 16,
    borderRadius: 10,
    fontSize: 10,
    fontWeight: 500,
    lineHeight: 1,
    whiteSpace: "nowrap" as const,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    boxSizing: "border-box" as const,
    flexShrink: 0,
  },
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    paddingLeft: 18,
    minWidth: 0,
    fontSize: 11,
  },
  age: {
    color: "var(--color-text-secondary)",
    whiteSpace: "nowrap" as const,
  },
  diff: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },
  additions: {
    color: "var(--color-additions)",
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
  },
  deletions: {
    color: "var(--color-deletions)",
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
  },
  authorBlock: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    flexShrink: 1,
  },
  avatar: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    flexShrink: 0,
  },
  authorName: {
    color: "var(--color-text-secondary)",
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  rowRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  reviewers: {
    display: "flex",
    alignItems: "center",
  },
  reviewerWrap: {
    position: "relative" as const,
    marginLeft: -4,
    width: 19,
    height: 19,
    flexShrink: 0,
  },
  reviewerAvatar: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    border: "1.5px solid var(--color-avatar-border)",
  },
  stateBadge: {
    position: "absolute" as const,
    bottom: -2,
    right: -3,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 11,
    height: 11,
    borderRadius: "50%",
    border: "1.5px solid var(--color-avatar-border)",
  },
  extraCount: {
    color: "var(--color-text-secondary)",
    fontSize: 10,
    marginLeft: 2,
    whiteSpace: "nowrap" as const,
  },
  comments: {
    display: "flex",
    alignItems: "center",
    gap: 3,
  },
  commentCount: {
    color: "var(--color-text-secondary)",
    fontSize: 11,
    whiteSpace: "nowrap" as const,
  },
};

export const badgeStyles: Record<string, React.CSSProperties> = {
  container: {
    position: "absolute",
    left: 0,
    top: "50%",
    transform: "translate(-50%, -50%)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    zIndex: 10,
  },
  box: {
    position: "relative" as const,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 26,
    height: 26,
    borderRadius: 5,
    border: "2px solid",
    background: "var(--color-page-bg)",
    padding: 0,
    flexShrink: 0,
  },
  notificationBubble: {
    position: "absolute" as const,
    top: -8,
    left: -6,
    minWidth: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "var(--color-behind)",
    color: "#fff",
    fontSize: 9,
    fontWeight: 700,
    lineHeight: "14px",
    textAlign: "center" as const,
    padding: "0 3px",
    boxSizing: "border-box" as const,
    pointerEvents: "none" as const,
  },
};
