export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: "flex",
    height: "100%",
    overflow: "hidden",
  },
  containerMobile: {
    flexDirection: "column" as const,
  },
  sidebar: {
    width: 300,
    flexShrink: 0,
    overflowY: "auto" as const,
    borderRight: "1px solid var(--color-border-subtle)",
    background: "var(--color-page-bg)",
    padding: "8px 0",
  },
  sidebarMobile: {
    width: "100%",
    maxHeight: "40%",
    borderRight: "none",
    borderBottom: "1px solid var(--color-border-subtle)",
  },
  sidebarHeader: {
    padding: "6px 16px 10px",
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: 0.4,
    color: "var(--color-text-secondary)",
  },
  sidebarMessage: {
    padding: "8px 16px",
    fontSize: 13,
    color: "var(--color-text-secondary)",
  },
  sidebarError: {
    padding: "8px 16px",
    fontSize: 13,
    color: "var(--color-error)",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "flex-start",
    gap: 8,
  },
  workflowItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "7px 16px",
    fontSize: 13,
    fontWeight: 500,
    border: "none",
    background: "transparent",
    color: "var(--color-text)",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 0.1s",
  },
  workflowName: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  workflowDisabledBadge: {
    marginLeft: "auto",
    fontSize: 11,
    fontWeight: 500,
    color: "var(--color-text-secondary)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 10,
    padding: "0 6px",
    flexShrink: 0,
  },
  runsList: {
    paddingBottom: 4,
  },
  runItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    padding: "6px 12px 6px 30px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 0.1s",
  },
  runItemSelected: {
    background: "var(--color-card-bg)",
    boxShadow: "inset 2px 0 0 var(--color-link)",
  },
  runItemIcon: {
    flexShrink: 0,
    marginTop: 2,
  },
  runItemBody: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 1,
    minWidth: 0,
  },
  runItemTitle: {
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--color-text)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  runItemMeta: {
    fontSize: 11.5,
    color: "var(--color-text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  loadMoreBtn: {
    display: "block",
    width: "100%",
    padding: "7px 16px",
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--color-link)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 0.1s",
  },
  loadMoreRunsBtn: {
    display: "block",
    width: "100%",
    padding: "6px 12px 6px 52px",
    fontSize: 12,
    fontWeight: 500,
    color: "var(--color-link)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "background 0.1s",
  },
  detail: {
    flex: 1,
    minWidth: 0,
    overflowY: "auto" as const,
    padding: 20,
  },
  detailMobile: {
    padding: 12,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 8,
    marginTop: 80,
    color: "var(--color-text-secondary)",
    fontSize: 14,
    textAlign: "center" as const,
    padding: "0 20px",
  },
  runHeader: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
    marginBottom: 12,
  },
  backRow: {
    marginBottom: 10,
  },
  backBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px 4px 8px",
    fontSize: 12.5,
    fontWeight: 500,
    borderRadius: 6,
    border: "1px solid var(--color-border-subtle)",
    background: "transparent",
    color: "var(--color-link)",
    cursor: "pointer",
  },
  runTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  runTitle: {
    fontSize: 16,
    fontWeight: 600,
    margin: 0,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  runNumber: {
    fontSize: 14,
    fontWeight: 400,
    color: "var(--color-text-secondary)",
    flexShrink: 0,
  },
  githubRunLink: {
    marginLeft: "auto",
    flexShrink: 0,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--color-link)",
    textDecoration: "none",
    whiteSpace: "nowrap" as const,
  },
  runMetaRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: "6px 14px",
    fontSize: 12.5,
    color: "var(--color-text-secondary)",
  },
  metaItem: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  },
  branchChip: {
    background: "var(--color-branch-bg)",
    color: "var(--color-branch)",
    borderRadius: 10,
    padding: "1px 8px",
    fontSize: 12,
    fontWeight: 500,
    maxWidth: 240,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  actorAvatar: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    flexShrink: 0,
  },
  timelineCard: {
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    padding: "12px 8px 8px",
    background: "var(--color-page-bg)",
  },
  cardMessage: {
    fontSize: 13,
    color: "var(--color-text-secondary)",
    margin: 0,
    padding: "20px 12px",
    textAlign: "center" as const,
  },
  cardError: {
    fontSize: 13,
    color: "var(--color-error)",
    margin: 0,
    padding: "20px 12px",
    textAlign: "center" as const,
  },
  trendCard: {
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-page-bg)",
    padding: "14px 14px 10px",
  },
  trendHeader: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
    marginBottom: 8,
  },
  trendTitle: {
    fontSize: 15,
    fontWeight: 600,
    margin: 0,
  },
  trendSubtitle: {
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--color-text-secondary)",
    margin: 0,
    maxWidth: 760,
  },
  trendBody: {
    width: "100%",
    minHeight: 120,
    // The plot has a minimum readable width; on a phone it scrolls inside the
    // card rather than stretching the whole view.
    overflowX: "auto" as const,
  },
  trendFooter: {
    display: "flex",
    flexWrap: "wrap" as const,
    alignItems: "center",
    justifyContent: "space-between",
    gap: "4px 16px",
    paddingTop: 6,
  },
  trendLegend: {
    display: "flex",
    flexWrap: "wrap" as const,
    alignItems: "center",
    gap: "4px 14px",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  trendLegendItem: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--color-text-secondary)",
  },
  trendLegendDot: {
    width: 9,
    height: 9,
    borderRadius: "50%",
    flexShrink: 0,
  },
  trendNote: {
    fontSize: 11.5,
    color: "var(--color-text-secondary)",
    margin: 0,
  },
  retryBtn: {
    padding: "4px 12px",
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 6,
    border: "1px solid var(--color-border-subtle)",
    background: "transparent",
    color: "var(--color-text)",
    cursor: "pointer",
  },
};
